import argparse

parser = argparse.ArgumentParser(description='MACIL_SD')
parser.add_argument('--modality', default='MIX2', help='the type of the input, AUDIO,RGB,FLOW, MIX1, MIX2, or MIX3, MIX_ALL')
parser.add_argument('--rgb-list', default='list/rgb.list', help='list of rgb features ')
parser.add_argument('--flow-list', default='list/flow.list', help='list of flow features')
parser.add_argument('--audio-list', default='list/audio.list', help='list of audio features')
parser.add_argument('--test-rgb-list', default='list/rgb_test.list', help='list of test rgb features ')
parser.add_argument('--test-flow-list', default='list/flow_test.list', help='list of test flow features')
parser.add_argument('--test-audio-list', default='list/audio_test.list', help='list of test audio features')
parser.add_argument('--model_dir', default='ckpt/macil_sd.pkl', help='ckpt dir')
parser.add_argument('--gt', default='list/gt.npy', help='file of ground truth ')
parser.add_argument('--gpus', default='0', type=str,  help='gpus')
parser.add_argument('--lr', type=float, default=0.0004, help='learning rate (default: 0.0001)')
parser.add_argument('--batch-size', type=int, default=128, help='number of instances in a batch of data (default: 128)')
parser.add_argument('--workers', default=8, help='number of workers in dataloader')
parser.add_argument('--model-name', default='macil_sd', help='name to save model')
parser.add_argument('--pretrained-ckpt', default=None, help='ckpt for pretrained model')
parser.add_argument('--num_classes', type=int, default=1, help='number of class')
parser.add_argument('--a_feature_size', type=int, default=128)
parser.add_argument('--v_feature_size', type=int, default=1024)
parser.add_argument('--m', type=float, default=0.91, help='update teacher model')
parser.add_argument('--dataset-name', default='XD-Violence', help='dataset to train on (default: )')
parser.add_argument('--max_seqlen', type=int, default=200, help='maximum sequence length during training (default: 750)')
parser.add_argument('--max-epoch', type=int, default=50, help='maximum iteration to train (default: 100)')
parser.add_argument('--lamda_a2b', type=float, default=1.5)
parser.add_argument('--lamda_a2n', type=float, default=1.5)
parser.add_argument('--lamda_cof', type=float, default=0.1)
parser.add_argument('--hid_dim', type=int, default=128)
parser.add_argument('--ffn_dim', type=int, default=128)
parser.add_argument('--num_stages', type=int, default=3)
parser.add_argument('--nhead', type=int, default=4)
parser.add_argument('--dropout', type=float, default=0.1)
